# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [2]:
import numpy as np

In [4]:
lst = [
    [1, 2, 3],
    [4 ,5, 6]
]

In [6]:
a = np.array(lst)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a[0,0]

1

In [8]:
b = np.arange(12).reshape(2,2,3)
print(b.shape)
b

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
print(b[0][0][0], b[0,0,0])
print(b[1,0,1])

0 0
7


In [11]:
b[1,0]

array([6, 7, 8])

In [12]:
b[0,1]

array([3, 4, 5])

In [13]:
b[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
arr = np.arange(10)
arr  # 1차원 배열

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[0], arr[2], arr[[0,2]]  #[[*,#]]의 구조로 *와 #을 한번에 추출할 수 있다.

(0, 2, array([0, 2]))

In [19]:
arr[[0,5,7]]

array([0, 5, 7])

In [3]:
arr2 = np.arange(12).reshape(3,4)  # 2차원 배열
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(arr2[0,1])
print(arr2[2,3])


# arr2[[0축], [1축]] 조회
print(arr2[[0,1],[2,3]])  # arr2의 [0,2]와 [1,3]의 자리를 조회
print(arr2[[0,2],[1,3]])  # arr2의 [0,1]과 [2,3]의 자리를 조회

1
11
[2 7]
[ 1 11]


In [33]:
# arr2의 4, 9, 3을 출력
arr2[[1, 2, 0] , [0, 1, 3]]

array([4, 9, 3])

In [37]:
arr[1] = 100  # 값 변경(대입)
arr

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
arr[2], arr[4] = 200, 400  # 튜플 대입
arr

array([  0, 100, 200,   3, 400,   5,   6,   7,   8,   9])

In [40]:
arr[[5, 7]] = 500, 700
arr

array([  0, 100, 200,   3, 400, 500,   6, 700,   8,   9])

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [41]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
arr[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [47]:
arr[50:20:-1]  # step 음수: 리버스(뒤집기), start > stop

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [49]:
arr[::-1]  # 전체 리버스

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [50]:
arr[-1:50:-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [6]:
a = np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
a[[1,1,1,2,2,2,3,3,3,4,4,4],[1,2,3,1,2,3,1,2,3,1,2,3]]

array([ 6,  7,  8, 11, 12, 13, 16, 17, 18, 21, 22, 23])

In [8]:
# a[[0축], [1축]] 조회
a[1:5, 1:4]  # 0번(세로)축은 1 ~ (5-1) / 1번(가로)축은 1 ~ (4-1)을 가져오는 것

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [67]:
a[1:5, :]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
a[1:5]  # 마지막 축은 다 가져오는 경우 생략 가능

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
a[:,1:3]  # 앞쪽 축은 생략 불가

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [71]:
a[:, [1, 2]]  # 슬라이싱과 인덱싱을 합쳐 사용할 수 있다.

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [72]:
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [73]:
np.flip(a, axis = 0)

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [75]:
np.flip(a)  # axis를 생략하면 다 리버스

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

In [76]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [79]:
b = a[:, 1:4]
b

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [80]:
b[0,0] = 10000
b

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [81]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [84]:
b = a[:, 1:4]
b = b.copy()
b

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [85]:
b[0,0] = 5000
b

array([[5000,    2,    3],
       [   6,    7,    8],
       [  11,   12,   13],
       [  16,   17,   18],
       [  21,   22,   23],
       [  26,   27,   28]])

In [86]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

## boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [9]:
import numpy as np

In [11]:
a = np.array([1, 2, 3, 4, 5])
a.shape

(5,)

In [12]:
b = np.array([True, True, False, False, False])
b.shape

(5,)

In [13]:
a[b]

array([1, 2])

In [14]:
a[[False, True, False, True, False]]

array([2, 4])

In [16]:
# 벡터화 (연산)
# 배열 + 배열 : 같은 인덱스의 원소들끼리 계산
# 배열 + scalar : 배열의 모든 원소들과 scalar를 연산

a = np.array([1,2,3])
b = np.array([10, 20, 30,])
a + b

array([11, 22, 33])

In [17]:
a + 20

array([21, 22, 23])

In [18]:
a > 2

array([False, False,  True])

In [21]:
arr = np.arange(100)
np.random.shuffle(arr)
arr

array([99, 76, 70, 91, 64, 87, 79, 14, 31, 33, 41, 34, 83, 53, 15, 42, 51,
       24, 35, 88, 61, 96, 95, 50, 82, 37, 54, 98, 32, 77, 45, 48, 52, 65,
       20, 38, 25, 55,  3, 22, 81, 58, 23, 78, 72,  8, 27, 17, 46, 84, 67,
       40,  4, 85, 29, 19, 10, 47,  5, 60, 30, 28, 89, 69, 80, 13, 62, 43,
       92, 68, 36, 73,  7, 71, 44,  9, 59, 11,  6, 21, 39,  0, 93, 12, 66,
       74, 94, 49,  2, 26, 86,  1, 63, 16, 75, 18, 57, 56, 97, 90])

In [22]:
# arr의 원소중에서 50이상인 값들만 조회
arr[arr>50]

array([99, 76, 70, 91, 64, 87, 79, 83, 53, 51, 88, 61, 96, 95, 82, 54, 98,
       77, 52, 65, 55, 81, 58, 78, 72, 84, 67, 85, 60, 89, 69, 80, 62, 92,
       68, 73, 71, 59, 93, 66, 74, 94, 86, 63, 75, 57, 56, 97, 90])

In [32]:
arr2 = np.arange(100).reshape(2,50)
np.random.shuffle(arr2[1])
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [71, 98, 74, 63, 94, 68, 65, 80, 73, 59, 77, 85, 93, 82, 88, 89,
        83, 53, 99, 72, 96, 67, 90, 61, 69, 62, 95, 50, 54, 91, 84, 86,
        51, 58, 79, 70, 60, 81, 66, 87, 57, 64, 78, 76, 92, 55, 75, 56,
        97, 52]])

In [34]:
arr2[arr2>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 71, 98, 74, 63, 94, 68, 65, 80, 73, 59, 77, 85, 93, 82, 88,
       89, 83, 53, 99, 72, 96, 67, 90, 61, 69, 62, 95, 50, 54, 91, 84, 86,
       51, 58, 79, 70, 60, 81, 66, 87, 57, 64, 78, 76, 92, 55, 75, 56, 97,
       52])

In [37]:
# 20 ~ 30
arr[(arr >= 20) & (arr <= 30)]

array([24, 20, 25, 22, 23, 27, 29, 30, 28, 21, 26])

In [40]:
# 50보다 크지 않은 값들을 조회
arr[~(arr>50)], arr[arr<=50]

(array([14, 31, 33, 41, 34, 15, 42, 24, 35, 50, 37, 32, 45, 48, 20, 38, 25,
         3, 22, 23,  8, 27, 17, 46, 40,  4, 29, 19, 10, 47,  5, 30, 28, 13,
        43, 36,  7, 44,  9, 11,  6, 21, 39,  0, 12, 49,  2, 26,  1, 16, 18]),
 array([14, 31, 33, 41, 34, 15, 42, 24, 35, 50, 37, 32, 45, 48, 20, 38, 25,
         3, 22, 23,  8, 27, 17, 46, 40,  4, 29, 19, 10, 47,  5, 30, 28, 13,
        43, 36,  7, 44,  9, 11,  6, 21, 39,  0, 12, 49,  2, 26,  1, 16, 18]))

## 넘파이에서 비교연산자
- 파이썬에서 비교연산자인 and, or, not 사용불가
- ' & ' : and
- ' | ' : or
- ' ~ ' : not
- 피연산자들은 ( )로 묶어줘야 한다.

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(booean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [45]:
a = np.array([True, False, True, False])
r = np.where(a) # True인 Index들을 튜플안에 ndarray를 담아서 반환
print(r)
print(type(r))
print(type(r[0]))

(array([0, 2]),)
<class 'tuple'>
<class 'numpy.ndarray'>


In [46]:
# arr에서 50 이상인 인덱스들을 조회
np.where(arr >= 50)

(array([ 0,  1,  2,  3,  4,  5,  6, 12, 13, 16, 19, 20, 21, 22, 23, 24, 26,
        27, 29, 32, 33, 37, 40, 41, 43, 44, 49, 50, 53, 59, 62, 63, 64, 66,
        68, 69, 71, 73, 76, 82, 84, 85, 86, 90, 92, 94, 96, 97, 98, 99]),)

In [52]:
# True는 '참', False는 '거짓'으로 변경 (원본은 그대로). 변경한 ndarray 객체를 반환
np.where(a, '참', '거짓')

array(['참', '거짓', '참', '거짓'], dtype='<U2')

In [50]:
a

array([ True, False,  True, False])

In [53]:
np.where(arr >= 50, '50 이상', '50 미만')

array(['50 이상', '50 이상', '50 이상', '50 이상', '50 이상', '50 이상', '50 이상',
       '50 미만', '50 미만', '50 미만', '50 미만', '50 미만', '50 이상', '50 이상',
       '50 미만', '50 미만', '50 이상', '50 미만', '50 미만', '50 이상', '50 이상',
       '50 이상', '50 이상', '50 이상', '50 이상', '50 미만', '50 이상', '50 이상',
       '50 미만', '50 이상', '50 미만', '50 미만', '50 이상', '50 이상', '50 미만',
       '50 미만', '50 미만', '50 이상', '50 미만', '50 미만', '50 이상', '50 이상',
       '50 미만', '50 이상', '50 이상', '50 미만', '50 미만', '50 미만', '50 미만',
       '50 이상', '50 이상', '50 미만', '50 미만', '50 이상', '50 미만', '50 미만',
       '50 미만', '50 미만', '50 미만', '50 이상', '50 미만', '50 미만', '50 이상',
       '50 이상', '50 이상', '50 미만', '50 이상', '50 미만', '50 이상', '50 이상',
       '50 미만', '50 이상', '50 미만', '50 이상', '50 미만', '50 미만', '50 이상',
       '50 미만', '50 미만', '50 미만', '50 미만', '50 미만', '50 이상', '50 미만',
       '50 이상', '50 이상', '50 이상', '50 미만', '50 미만', '50 미만', '50 이상',
       '50 미만', '50 이상', '50 미만', '50 이상', '50 미만', '50 이상', '50 이상',
       '50 이상', '50 

In [55]:
# 50 이상인 값은 '50 이상'으로 변경하고, 50 미만인 값은 그대로 나오도록
np.where(arr >= 50, '50 이상', arr)

array(['50 이상', '50 이상', '50 이상', '50 이상', '50 이상', '50 이상', '50 이상',
       '14', '31', '33', '41', '34', '50 이상', '50 이상', '15', '42',
       '50 이상', '24', '35', '50 이상', '50 이상', '50 이상', '50 이상', '50 이상',
       '50 이상', '37', '50 이상', '50 이상', '32', '50 이상', '45', '48',
       '50 이상', '50 이상', '20', '38', '25', '50 이상', '3', '22', '50 이상',
       '50 이상', '23', '50 이상', '50 이상', '8', '27', '17', '46', '50 이상',
       '50 이상', '40', '4', '50 이상', '29', '19', '10', '47', '5', '50 이상',
       '30', '28', '50 이상', '50 이상', '50 이상', '13', '50 이상', '43',
       '50 이상', '50 이상', '36', '50 이상', '7', '50 이상', '44', '9', '50 이상',
       '11', '6', '21', '39', '0', '50 이상', '12', '50 이상', '50 이상',
       '50 이상', '49', '2', '26', '50 이상', '1', '50 이상', '16', '50 이상',
       '18', '50 이상', '50 이상', '50 이상', '50 이상'], dtype='<U21')

In [58]:
# 0: 여성, 1: 남성
gender = np.random.choice([0, 1], size = 20)
gender

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0])

In [59]:
np.where(gender, '남성', '여성')

array(['여성', '남성', '여성', '여성', '여성', '여성', '여성', '남성', '여성', '여성', '여성',
       '여성', '여성', '남성', '남성', '여성', '남성', '여성', '남성', '여성'], dtype='<U2')

- 2차원도 마찬가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

In [63]:
arr2 = [
    [1, 10, 7],
    [4, 2, 10],
    [10, 2, 8]
]
arr2 = np.array(arr2)
arr2

array([[ 1, 10,  7],
       [ 4,  2, 10],
       [10,  2,  8]])

In [69]:
r = np.where(arr2 >= 5)
print(type(r))
r
# (0, 1), (0, 2), (1, 2), (2, 0), (2, 2)이 True인 애들이므로 출력결과와 비교해보기

<class 'tuple'>


(array([0, 0, 1, 2, 2]), array([1, 2, 2, 0, 2]))

In [70]:
np.where(arr2 >= 5, '크다', '작다')

array([['작다', '크다', '크다'],
       ['작다', '작다', '크다'],
       ['크다', '작다', '크다']], dtype='<U2')

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [74]:
np.any([True, False, False, True]), np.any([False, False])

(True, False)

In [75]:
np.all([True, True]), np.all([True, False, True, True])

(True, False)

In [76]:
arr

array([99, 76, 70, 91, 64, 87, 79, 14, 31, 33, 41, 34, 83, 53, 15, 42, 51,
       24, 35, 88, 61, 96, 95, 50, 82, 37, 54, 98, 32, 77, 45, 48, 52, 65,
       20, 38, 25, 55,  3, 22, 81, 58, 23, 78, 72,  8, 27, 17, 46, 84, 67,
       40,  4, 85, 29, 19, 10, 47,  5, 60, 30, 28, 89, 69, 80, 13, 62, 43,
       92, 68, 36, 73,  7, 71, 44,  9, 59, 11,  6, 21, 39,  0, 93, 12, 66,
       74, 94, 49,  2, 26, 86,  1, 63, 16, 75, 18, 57, 56, 97, 90])

In [77]:
# arr안에 50을 초과하는 값이 하나라도 있는 지 확인하는 것
np.any(arr > 50)

True

In [79]:
# arr의 모든 값들이 50을 초과하는 지 확인하는 것
np.all(arr > 50)

False

In [81]:
# 50 초과인 값이 몇개인지 확인하는 것
# sum(): 배열 내 원소의 총 합계 / boolean 배열 -> True = 1, False = 0으로 처리 후 계산

np.sum(arr > 50)

49

### 정렬
- np.sort(arr) / ndarray(배열객체).sort(): arr을 정렬
    - np.sort(arr): 배열을 정렬한 결과를 가진 새로운 배열을 반환(카피본), 원본은 바뀌지 않는다.
    - 배열.sort(): 원본 배열을 정렬 
- np.argsort(arr): 정렬 후 index를 반환
- 오름차순 정렬만 지원. 내림차순을 할 경우, 정렬 후 reverse 해야 한다.

In [85]:
x = np.sort(arr)
x, arr

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([99, 76, 70, 91, 64, 87, 79, 14, 31, 33, 41, 34, 83, 53, 15, 42, 51,
        24, 35, 88, 61, 96, 95, 50, 82, 37, 54, 98, 32, 77, 45, 48, 52, 65,
        20, 38, 25, 55,  3, 22, 81, 58, 23, 78, 72,  8, 27, 17, 46, 84, 67,
        40,  4, 85, 29, 19, 10, 47,  5, 60, 30, 28, 89, 69, 80, 13, 62, 43,
        92, 68, 36, 73,  7, 71, 44,  9, 59, 11,  6, 21, 39,  0, 93, 12, 66,
        74, 94, 49,  2, 26, 86,  1, 63, 16, 75, 18, 57, 56, 97, 90]))

In [86]:
# arr.sort()는 자신을 정렬하고 반환값을 주지 않는 것이기 때문에 y는 None이 나온다.
y = arr.sort()
print(y)

None


In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [90]:
# 내림차순 정렬을 하고 싶다 -> reverse 과정이 따로 필요
arr[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [92]:
a = np.array([3, 1, 5, 2])
a

array([3, 1, 5, 2])

In [93]:
np.sort(a)[::-1]

array([5, 3, 2, 1])

In [95]:
# index를 오름차순으로 정렬
np.argsort(a)

array([1, 3, 0, 2])

In [96]:
np.argsort(a)[::-1]  # 내림차순

array([2, 0, 3, 1])

In [98]:
a[np.argsort(a)]  # a의 값들로 출력

array([1, 2, 3, 5])

In [99]:
l = [
    [3, 1, 5],
    [1, 2, 9],
    [10, 20, 5]
]
b = np.array(l)
b

array([[ 3,  1,  5],
       [ 1,  2,  9],
       [10, 20,  5]])

In [103]:
np.sort(b)  # 다차원 배열 정렬에서 AXIS를 생략하면 마지막 축을 기준으로 정렬

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])

In [104]:
np.sort(b, axis = 0) # 0번 축 기준으로 정렬

array([[ 1,  1,  5],
       [ 3,  2,  5],
       [10, 20,  9]])

In [105]:
np.sort(b, axis = 1) # 1번 축 기준으로 정렬

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])