# 배열의 형태(shape) 변경

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.
    - 원본 배열은 변경시키지 않는다. (shape을 바꾼 새로운 배열(카피본)을 반환한다.)

In [1]:
import numpy as np

In [2]:
a = np.arange(20)
print(a.shape)
print(a.size)
a

(20,)
20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
b = np.reshape(a, (4, 5))
print(b.shape)
print(b.size)
b

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
c = a.reshape(4,5)
print(c.shape)
print(c.size)
c

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
d = a.reshape(2,2,5)
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [9]:
# reshape하고자 하는 사이즈가 기존 사이즈와 다르면 에러발생
e = a.reshape(3,3)
e

ValueError: cannot reshape array of size 20 into shape (3,3)

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
f = np.arange(5*5*5).reshape(5,5,5)
f

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [13]:
f_1 = np.reshape(f, 125)  # reshape에 정수를 넣으면 1차원으로 변환해준다.
print(f_1.shape)
f_1

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

- newshape를 지정할 때 특정 축에 -1을 주면 원소 수에 맞춰서 size를 정한다. (전체 축 중에 하나만 사용가능)

In [14]:
f_2 = np.reshape(f, -1)
print(f_2.shape)
f_2

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
a_1 = np.reshape(a, (5,-1))  # a는 20개인데, (5,-1)을 주면 -1의 자리에는 무조건 4가 오게 될 수 밖에 없음 -> 자동 계산
print(a_1.shape)
a_1

(5, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## 차원 늘리기(확장)

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 축(axis)을 늘릴때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    

In [17]:
a = np.arange(1, 6)
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


In [18]:
# (5,) -> (1, 5)
x = a[np.newaxis, :]
print(x.shape)
x

(1, 5)


array([[1, 2, 3, 4, 5]])

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
# a: (5, ) -> y: (5, 1)
y = a[:, np.newaxis]
print(y.shape)
y

(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [23]:
# a: (5, ) -> z: (1, 5, 1)
z = a[np.newaxis, :, np.newaxis]
print(z.shape)
z

(1, 5, 1)


array([[[1],
        [2],
        [3],
        [4],
        [5]]])

In [24]:
b = np.arange(6).reshape(2,3)
print(b.shape)
b

(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
# b: (2, 3) -> m: (1, 2, 3)
m = b[np.newaxis, :, :]
print(m.shape)
m

(1, 2, 3)


array([[[0, 1, 2],
        [3, 4, 5]]])

In [29]:
# (2, 3) -> (2, 1, 3, 1)
o = b[:, np.newaxis, :, np.newaxis]
o.shape

(2, 1, 3, 1)

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [31]:
# (2, 3, 4) -> (1, 2, 3, 4)
a = np.arange(24).reshape(2, 3, 4)
print(a.shape)
b = a[np.newaxis, ...]
print(b.shape)

(2, 3, 4)
(1, 2, 3, 4)


### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.

In [33]:
a = np.array([1, 2, 3, 4, 5])
print(a.shape)

(5,)


In [34]:
# (5, ) -> (5,1)
a1 = np.expand_dims(a, axis = 1)
a1.shape

(5, 1)

In [35]:
# (5,) -> (1, 5)
a2 = np.expand_dims(a, axis = 0)
a2.shape

(1, 5)

In [38]:
b = np.arange(6)
b = np.array(b).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
# (2, 3) -> (2, 1, 3)
b1 = np.expand_dims(b, axis = 1)
b1.shape

(2, 1, 3)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [46]:
a = np.arange(12).reshape(1,2,1,2,3,1)
a.shape

(1, 2, 1, 2, 3, 1)

In [47]:
b = np.squeeze(a)
b.shape

(2, 2, 3)

In [49]:
c = np.squeeze(a, axis = 2) 
c.shape

(1, 2, 2, 3, 1)

In [50]:
c = np.squeeze(a, axis = 3)  # size가 1이 아닌 축은 제거할 수 없다.
c.shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [52]:
# (2, 3) -> (6, )
# (2, 2, 2, 3) -> (24, )
a = np.arange(20).reshape(2,2,5)
a.shape

(2, 2, 5)

In [55]:
a2 = a.flatten()
a2.shape

(20,)

In [57]:
a  # 원본이 바뀌진 않는다.

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

In [58]:
a = np.array([1, 2, 3])

In [60]:
r = np.append(a, 100)  # 1개의 값을 추가
r

array([  1,   2,   3, 100])

In [61]:
r = np.append(a, [100, 200, 300])
r

array([  1,   2,   3, 100, 200, 300])

In [153]:
l = [
    [1, 1],
    [2, 2],
    [3, 3]    
]
b = np.array(l)
print(b.shape)
b

(3, 2)


array([[1, 1],
       [2, 2],
       [3, 3]])

In [156]:
r = np.append(b, [[4, 4]], axis = 0)
r

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [70]:
r = np.append(b, [[4, 4],[5, 5],[6, 6]], axis = 0)
r

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

In [71]:
r = np.append(b, [[1], [2], [3]], axis = 1)
r

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [72]:
# axis를 생략하면, flatten 후에 append를 처리한다.
np.append(b, [100, 200])

array([  1,   1,   2,   2,   3,   3, 100, 200])

### insert

In [73]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [75]:
r = np.insert(a, 0, 100)  # index = 0에 100을 삽입하겠다.
r

array([100,   1,   2,   3])

In [76]:
r = np.insert(a, 2, 200)
r

array([  1,   2, 200,   3])

In [77]:
r = np.insert(a, 1, [10, 20, 30])
r

array([ 1, 10, 20, 30,  2,  3])

In [78]:
b = np.array([[1, 1], [2, 3], [3, 3]])
b

array([[1, 1],
       [2, 3],
       [3, 3]])

In [80]:
np.insert(b, 1, 100)  # axis를 생략


array([  1, 100,   1,   2,   3,   3,   3])

In [84]:
np.insert(b, 1, [10, 10], axis = 0)

array([[ 1,  1],
       [10, 10],
       [ 2,  3],
       [ 3,  3]])

In [85]:
np.insert(b, 2, 100, axis = 0)  # 동일한 값을 넣을 때는 한번만 정수로 써서 넣을 수 있다.

array([[  1,   1],
       [  2,   3],
       [100, 100],
       [  3,   3]])

In [86]:
np.insert(b, 1, [100, 200, 300], axis = 1)

array([[  1, 100,   1],
       [  2, 200,   3],
       [  3, 300,   3]])

In [88]:
np.insert(b, 1, [[100, 200, 300], [5, 6, 7]], axis = 1)

array([[  1, 100,   5,   1],
       [  2, 200,   6,   3],
       [  3, 300,   7,   3]])

### delete

In [89]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
r = np.delete(a, 0)
r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
r = np.delete(a, [2, 5, 6])
r

array([0, 1, 3, 4, 7, 8, 9])

In [97]:
# slicing을 이용해서 삭제
# slicing을 함수의 매개변수로 전달할 경우: np.s_[slicing]
one = np.delete(a, a[2:7])
two = np.delete(a, np.s_[2:7])
one, two

(array([0, 1, 7, 8, 9]), array([0, 1, 7, 8, 9]))

In [98]:
b = np.arange(36).reshape(6,6)
b.shape

(6, 6)

In [99]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [101]:
np.delete(b, [0, 1], axis = 0)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [102]:
np.delete(b, [0, 1], axis = 1)

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29],
       [32, 33, 34, 35]])

In [104]:
# axis를 선언하지 않은 경우, flatten()후에 delete()
np.delete(b, [0, 1])

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

a: (3, 2) b: (3, 5) axis = 1 -> (3, 7)
a: (4, 2) b: (4, 2) axis = 0 -> (8, 2), axis = 1 -> (4, 4)
a: (2, 3, 5) b: (3, 1, 5) XXX
a: (2, 3, 5) b: (7, 3, 5) axis = 0 -> (9, 3, 5)

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

In [113]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])
c = np.array([100, 200])

# 1차원 배열 합치기
d = np.concatenate([a, b])
d

array([ 1,  2,  3, 10, 20, 30, 40])

In [115]:
e = np.concatenate([b, a])
e

array([10, 20, 30, 40,  1,  2,  3])

In [116]:
np.concatenate([a, b, c])

array([  1,   2,   3,  10,  20,  30,  40, 100, 200])

In [118]:
x = np.arange(6).reshape(2, 3)
y = np.arange(10, 16).reshape(2, 3)
z = np.arange(20, 26).reshape(2, 3)
print(x.shape, y.shape, z.shape)

(2, 3) (2, 3) (2, 3)


In [120]:
r = np.concatenate([x, y], axis = 0)
print(r.shape)
r

(4, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [121]:
r = np.concatenate([x, y], axis = 1)
print(r.shape)
r

(2, 6)


array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [122]:
r = np.concatenate([x, y, z], axis = 1)
print(r.shape)
r

(2, 9)


array([[ 0,  1,  2, 10, 11, 12, 20, 21, 22],
       [ 3,  4,  5, 13, 14, 15, 23, 24, 25]])

In [124]:
w = np.arange(10).reshape(2,5)
print(w.shape)
w

(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [129]:
np.concatenate([x, w], axis = 0)  # (2, 3)와 (2, 5)를 합치는데, 0축을 기준으로 합치면 3과 5가 맞지 않기 때문에 오류 발생

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [130]:
np.concatenate([x, w], axis = 1)

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

In [131]:
a = np.arange(12).reshape(2,2,3)
a.shape

(2, 2, 3)

In [132]:
b = np.arange(2*2*7).reshape(2,2,7)
b.shape

(2, 2, 7)

In [136]:
r = np.concatenate([a, b], axis = 2)
print(r.shape)
r

(2, 2, 10)


array([[[ 0,  1,  2,  0,  1,  2,  3,  4,  5,  6],
        [ 3,  4,  5,  7,  8,  9, 10, 11, 12, 13]],

       [[ 6,  7,  8, 14, 15, 16, 17, 18, 19, 20],
        [ 9, 10, 11, 21, 22, 23, 24, 25, 26, 27]]])

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

In [137]:
x.shape, y.shape, z.shape

((2, 3), (2, 3), (2, 3))

In [138]:
np.vstack([x, y])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [139]:
np.vstack([x, y, z])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [20, 21, 22],
       [23, 24, 25]])

In [140]:
w.shape

(2, 5)

In [146]:
np.vstack([x, w])  # 세로방향으로 스택을 쌓을 시, 3과 5로 사이즈가 다르기 때문에 오류 발생
# 1 축의 개수가 같아야 한다.

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [147]:
np.hstack([x, w])

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

In [148]:
np.hstack([x, y])

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [149]:
np.hstack([x, y, z])

array([[ 0,  1,  2, 10, 11, 12, 20, 21, 22],
       [ 3,  4,  5, 13, 14, 15, 23, 24, 25]])

In [152]:
np.hstack([x, w])
# 0 축의 개수가 같으면 된다.

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할 (동일한 크기로 나눠야 하므로, 나누어 떨어져야 한다.)
        - 리스트 : 분할 기준 index들  /  ex)length = 9, index = 5, 7 -> 1 ~ 4 / 5 ~ 7 / 8 ~ 9 이런식으로
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
r = np.split(a, 2)  # 2개로 분할
print(type(r))
print(r[0], type(r[0]))
print(r[1], type(r[1]))

<class 'list'>
[0 1 2 3 4] <class 'numpy.ndarray'>
[5 6 7 8 9] <class 'numpy.ndarray'>


In [7]:
np.split(a, 3)  # 3개로 분할 -> 10개를 3으로 나눌 수 없기 때문에 에러 발생
# 분할된 배열의 크기가 동일해야 한다.

ValueError: array split does not result in an equal division

In [8]:
r = np.split(a, [2, 6])  # index 2, 6을 기준으로 분할해라 -> 3조각으로 분할
print(r)

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]


In [10]:
r = np.split(a, [4])  # [4]: 4를 기준으로 분할 / 4: 4개로 분할
r

[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8, 9])]

In [12]:
b = np.arange(16).reshape(4,4)
print(b.shape)
b

(4, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.split(b, 2)  # axis 기본값 = 0

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [15]:
np.split(b, 2, axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [17]:
r = np.split(b, [1], axis = 0)
r

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [18]:
r = np.split(b, [1, 3], axis = 0)
r

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [39]:
c = np.arange(6*6*8).reshape(6,6,8)
c.shape

(6, 6, 8)

In [40]:
r = np.split(c, 2, axis = 0)  # 3 * 6 * 8의 배열로 2개 분리
print(r[0].shape, r[1].shape)

(3, 6, 8) (3, 6, 8)


In [42]:
r = np.split(c, [2, 5], axis = 2)
print(r[0].shape, r[1].shape, r[2].shape)

(6, 6, 2) (6, 6, 3) (6, 6, 3)


## hsplit()/vsplit()

In [43]:
c = np.arange(64).reshape(8,8)
c.shape

(8, 8)

In [46]:
# vsplit() = split(axis = 0)
r = np.vsplit(c, 4)
print(r[0].shape, r[1].shape, r[2].shape, r[3].shape)

(2, 8) (2, 8) (2, 8) (2, 8)


In [47]:
# hsplit() = split(axis = 1)
r = np.hsplit(c, 4)
print(r[0].shape, r[1].shape, r[2].shape, r[3].shape)

(8, 2) (8, 2) (8, 2) (8, 2)


In [49]:
r = np.vsplit(c, [3, 6])
print(r[0].shape, r[1].shape, r[2].shape)

(3, 8) (3, 8) (2, 8)


In [50]:
r = np.hsplit(c, [2, 5])
print(r[0].shape, r[1].shape, r[2].shape)

(8, 2) (8, 3) (8, 3)
